
import shelve
import cPickle
from _02_regnet_generator import dict_to_model
from _03_database_functions import encode_gps, encode_gps_full, export_STG
from _03_database_functions import decode_gps_full
from _08_STG_reducer import subparset
from _12_AL_model_checker import filter_byAL

def remove_zero_edges(networks):
    print "found", len(networks), "networks.\nremoving null edges...",
    for nw in networks:
        networks[nw] = dict((k, v) for (k, v) in networks[nw].items() if v!='0')
    print "done."
    return networks
    
def lookup_graph_number(interactions): # because dicts are non-hashable, we cannot just revert allnetworks
    #print "looking up graph:", interactions
    for nw in allnetworks:
        #print "checking:", allnetworks[nw]
        if allnetworks[nw]==interactions:
            return nw
    # only executed if never found:
    print "interaction graph not found!"
    return -1

def lookup_iso_rep(number):
    for isoclass in isoclasses:
        if number in isoclasses[isoclass]:
            return isoclass
    # only executed if never found:
    print "isomorphism representative not found!"
    return -1

if __name__=='__main__':
    networks = dict()
    for letter in 'ABDEF': # in C, unfortunately green is the input gene
        networks[letter] = dict()
    
    networks['A']['name'] = '(A) Incoherent type 1 feed-forward'
    networks['A']['interactions'] = {("rr","gg"):"+", ("rr","bb"):"+", ("bb","gg"):"-", ("gg","gg"):"+"}
    
    networks['B']['name'] = '(B) Mutual inhibition'
    networks['B']['interactions'] = {("rr","gg"):"+", ("rr","bb"):"+", ("bb","gg"):"-", ("gg","bb"):"-"}
    
    networks['D']['name'] = '(D) Overlapping domains'
    networks['D']['interactions'] = {("rr","gg"):"-", ("rr","bb"):"+", ("bb","gg"):"+", ("gg","rr"):"-"}
    
    networks['E']['name'] = '(E) Bistable'
    networks['E']['interactions'] = {("rr","gg"):"-", ("gg","bb"):"-", ("bb","gg"):"+", ("bb","bb"):"+"}
    
    networks['F']['name'] = '(F) Classical'
    networks['F']['interactions'] = {("rr","gg"):"-", ("rr","bb"):"-", ("bb","gg"):"-", ("gg","gg"):"+", ("bb","bb"):"+"}
    
    allnetworks = cPickle.load(file("all_networks.db"))
    allnetworks = remove_zero_edges(allnetworks)
    
    combined_results_shelvenames = ["combined_results_AL.db", "combined_results.db"]

    iso_classes_name = "isomorphy_classes_without_morphogene.db"
    isoclasses = cPickle.load(file(iso_classes_name))
    #print isoclasses
    
    for crsname in combined_results_shelvenames:
        print "========================================="
        print "using results from:", crsname
        crs = shelve.open(crsname)
        for net in networks:
            print net #, networks[net]['interactions']
            graph_number = lookup_graph_number(networks[net]['interactions'])
            iso_graph_number = lookup_iso_rep(graph_number) 
            print iso_graph_number 
            print crs[str(iso_graph_number)]

    print "========================================="
    print "AL model checking"
    crs = shelve.open(combined_results_shelvenames[0])
    numbers = {7747:'A', 7423:'B', 7969:'E', 9349:'D', 14284:'F'} # TODO: this should be generated by the above loop (simple)
    combis = [(False, False), (True, False), (False, True)] # low, medium, high

    ALformulas = ["?(left: left.frozen(gg)&left.max(gg)=0)", "?(middle: middle.frozen(gg)&middle.min(gg)=1)",
                  "?(right: right.frozen(gg)&right.max(gg)=0)"]
    for number in numbers:
        mc = dict_to_model(allnetworks[number], add_morphogene=True)
        smallmc = dict_to_model(allnetworks[number], add_morphogene=False)
        gpss = mc._psc.get_parameterSets()
        count_accepted = 0
        for gps in gpss:
            #print gps
            subgps = dict((combi, encode_gps_full(subparset(gps, is_m1_in=combi[0], is_m2_in=combi[1]))) for combi in combis)
            parameter_set_IG_list = [decode_gps_full(subgps[combi]) for combi in combis]
            parameter_sets = [elem[0] for elem in parameter_set_IG_list]
            #print parameter_sets
            accepted = all(filter_byAL(smallmc, parameter_sets[i], ALformulas[i]) for i in range(3))*1
            if accepted:
                print "accepting:", gps
                #export_STG(mc, gps, filename=str(number).zfill(5)+"_"+encode_gps(gps, base=10)+".gml", initialRules=None)
                export_STG(mc, gps, filename="_"+numbers[number]+"_"+encode_gps(gps, base=10)+".gml", initialRules=None)
